Add app version to menu
Kyome22/RunCat_for_windows pull request #106
Opened 2022-07-12 14:57 UTC by somnisomni

![Screenshot after applying this change](https://user-images.githubusercontent.com/82272900/178520154-c1b1c716-c167-4456-b6db-8f25020b3a1e.png)

Just a small addition: Application version in RunCat's menu.  
This will help users identify what version of RunCat is running easily.

2022-07-13 07:41 UTC, Kyome22 requested changes

2022-07-13 07:41 UTC, Kyome22 commented on RunCat/Program.cs
> +                new ToolStripMenuItem($"{Application.ProductName} v{Application.ProductVersion}") { Enabled = false },
@somnisomni 
It is the best PR.
However, please apply indentation.

```c#
new ToolStripMenuItem($"{Application.ProductName}v{Application.ProductVersion}")
{
    Enabled = false
};
```

2022-07-13 13:28 UTC, somnisomni commented on RunCat/Program.cs
> +                new ToolStripMenuItem($"{Application.ProductName} v{Application.ProductVersion}") { Enabled = false },
Got it, indentation applied by force-pushing

2022-07-16 06:00 UTC, Kyome22 commented
LGTM！

2022-07-16 06:00 UTC, merged